name: Workflows should run on another repo
on:
  workflow_dispatch:
    inputs:
       client_payload:
          description: The Client payload
          required: true
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
    - name: python-code-scanning
      run: echo hello world
      with:
        dispatch_type: workflow
